import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'auth',
  owns: [
    'packages/auth/**',
    'apps/api/src/auth/**',
    'apps/api/src/middleware/require*',
    'apps/api/src/routes/invite*',
    'apps/api/src/routes/organization*',
    'apps/api/src/routes/permission*',
    'apps/api/src/policies/**',
  ],
  allowedReads: [
    'packages/auth/**',
    'apps/api/src/auth/**',
    'apps/api/src/middleware/**',
    'apps/api/src/routes/**',
    'apps/api/src/policies/**',
    'tests/auth/**',
    'tests/integration/auth/**',
    'apps/api/src/db/schema/users*',
    'apps/api/src/db/schema/sessions*',
    'apps/api/src/db/schema/roles*',
    'apps/api/src/db/migrations/*role*',
    'apps/api/src/db/migrations/*invite*',
    'apps/api/src/db/migrations/*permission*',
  ],
  allowedWrites: [
    'packages/auth/**',
    'apps/api/src/auth/**',
    'apps/api/src/policies/**',
    'apps/api/src/middleware/require*',
    'tests/auth/**',
    'tests/integration/auth/**',
  ],
  relatedDomains: ['backend', 'database', 'tests', 'frontend', 'security'],
  forbiddenByDefault: [
    'billing/**',
    'infra/**',
    'secrets/**',
    'apps/web/**',
  ],
  riskProfile: [
    'permissions',
    'security',
    'account access',
    'role mapping',
    'session handling',
    'multi-tenant access',
  ],
  verification: [
    'auth regression tests',
    'invite API tests',
    'permission boundary tests',
    'role normalization tests',
    'SSO callback tests',
    'session lifecycle tests',
  ],
  graphNodeIds: [
    'domain:auth',
    'route:POST /orgs/:id/invites',
    'route:GET /orgs/:id/invites',
    'symbol:requireOrgAdmin',
    'symbol:requireRole',
    'symbol:normalizeRole',
  ],
  graphEdgeIds: [
    'edge:invite_route→requireOrgAdmin',
    'edge:requireOrgAdmin→policy:org_admin',
    'edge:role_normalization→session',
  ],
  reviewSensitivity: 'critical',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'auth.trace_permission_check',
    domain: 'auth',
    category: 'auth',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source', 'read_policies'],
    description:
      'Trace a permission check end-to-end. Returns the guard, the role source, and the failure point.',
    inputHints: ['actor', 'action', 'resource', 'role'],
    tags: ['permission', 'role', 'guard', 'authorization', 'authz'],
    suggestedFollowUps: [
      'auth.find_policy_sources',
      'auth.explain_role_mapping',
      'tests.find_related_tests',
    ],
  },
  {
    name: 'auth.find_policy_sources',
    domain: 'auth',
    category: 'auth',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source', 'read_policies'],
    description:
      'Locate the policy file(s) responsible for the current guard. Returns path + rule ids.',
    inputHints: ['guard', 'role', 'permission'],
    tags: ['policy', 'role', 'permission'],
    suggestedFollowUps: ['auth.explain_role_mapping', 'auth.find_auth_callers'],
  },
  {
    name: 'auth.find_auth_callers',
    domain: 'auth',
    category: 'auth',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description:
      'List all callers of an auth symbol (guard, policy, role helper). Supports impact analysis before refactor.',
    inputHints: ['symbol'],
    tags: ['callers', 'impact', 'refactor'],
    suggestedFollowUps: ['auth.trace_permission_check', 'tests.find_related_tests'],
  },
  {
    name: 'auth.explain_role_mapping',
    domain: 'auth',
    category: 'auth',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_source', 'read_policies'],
    description:
      'Explain how a raw role value (e.g. SSO provider role) is normalized to the canonical Forge role set.',
    inputHints: ['role', 'provider', 'actor'],
    tags: ['role', 'mapping', 'sso', 'normalize'],
    suggestedFollowUps: ['auth.trace_permission_check', 'db.find_migrations_touching_table'],
  },
  {
    name: 'auth.get_invite_policy',
    domain: 'auth',
    category: 'auth',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_policies', 'read_source'],
    description:
      'Return the invite policy: who can invite, required role, expiry defaults, audit obligations.',
    inputHints: [],
    tags: ['invite', 'policy'],
    suggestedFollowUps: ['auth.find_policy_sources', 'db.get_table_schema'],
  },
  {
    name: 'auth.run_auth_regression_tests',
    domain: 'auth',
    category: 'auth',
    risk: 'medium',
    cost: 'medium',
    gain: 'high',
    requiredPermissions: ['run_test'],
    description:
      'Run the auth regression suite (permission boundaries, role normalization, invite flow).',
    inputHints: ['scope'],
    tags: ['test', 'regression', 'auth'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
]

export const authDomain: DomainEntry = Object.freeze({ manifest, capabilities })
