import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'backend',
  owns: [
    'apps/api/src/**',
    'apps/api/src/routes/**',
    'apps/api/src/services/**',
    'apps/api/src/controllers/**',
    'apps/api/src/validators/**',
    'apps/api/src/server.ts',
    'apps/api/src/index.ts',
    'apps/api/src/middleware/**',
    'apps/api/src/lib/**',
  ],
  allowedReads: [
    'apps/api/**',
    'packages/auth/**',
    'packages/shared/**',
    'apps/api/src/db/schema/**',
    'apps/api/src/db/migrations/**',
    'tests/api/**',
    'tests/integration/**',
  ],
  allowedWrites: [
    'apps/api/src/routes/**',
    'apps/api/src/services/**',
    'apps/api/src/controllers/**',
    'apps/api/src/validators/**',
    'apps/api/src/middleware/**',
    'apps/api/src/lib/**',
    'tests/api/**',
    'tests/integration/**',
  ],
  relatedDomains: ['auth', 'database', 'tests', 'frontend', 'infra'],
  forbiddenByDefault: [
    'apps/web/**',
    'billing/**',
    'secrets/**',
    'infra/**',
  ],
  riskProfile: [
    'public APIs',
    'request handling',
    'concurrency',
    'API compatibility',
    'data validation',
  ],
  verification: [
    'api integration tests',
    'route unit tests',
    'validator tests',
    'middleware tests',
    'error handling tests',
  ],
  graphNodeIds: [
    'domain:backend',
    'app:api',
    'route:POST /orgs/:id/invites',
    'route:GET /orgs/:id/invites',
    'service:InviteService',
    'service:OrganizationService',
  ],
  graphEdgeIds: [
    'edge:InviteService→InviteRepo',
    'edge:InviteRoute→InviteService',
    'edge:InviteService→EmailProvider',
  ],
  reviewSensitivity: 'high',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'backend.find_route_handler',
    domain: 'backend',
    category: 'general',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Locate the route handler (controller / service entry) for a given HTTP route.',
    inputHints: ['method', 'path'],
    tags: ['route', 'handler', 'controller', 'http'],
    suggestedFollowUps: ['backend.find_service_callers', 'tests.find_related_tests'],
  },
  {
    name: 'backend.find_service_callers',
    domain: 'backend',
    category: 'general',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'List all callers of a service method. Used to estimate refactor blast radius.',
    inputHints: ['service', 'method'],
    tags: ['callers', 'service', 'impact'],
    suggestedFollowUps: ['tests.find_related_tests', 'db.check_query_impact'],
  },
  {
    name: 'backend.find_request_validators',
    domain: 'backend',
    category: 'general',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Find request validators (zod, joi, class-validator) for a given route.',
    inputHints: ['route', 'method'],
    tags: ['validator', 'request', 'schema'],
    suggestedFollowUps: ['tests.find_related_tests'],
  },
  {
    name: 'backend.explain_error_path',
    domain: 'backend',
    category: 'general',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Trace how a given HTTP error code (e.g. 403, 422) is produced — which guard or service throws it.',
    inputHints: ['status', 'route'],
    tags: ['error', 'http', 'status', 'guard'],
    suggestedFollowUps: ['auth.trace_permission_check', 'tests.find_related_tests'],
  },
  {
    name: 'backend.run_api_smoke_tests',
    domain: 'backend',
    category: 'verification',
    risk: 'medium',
    cost: 'medium',
    gain: 'high',
    requiredPermissions: ['run_test', 'run_command'],
    description: 'Run the API integration smoke suite (auth, invites, organization).',
    inputHints: ['scope'],
    tags: ['test', 'integration', 'api'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
]

export const backendDomain: DomainEntry = Object.freeze({ manifest, capabilities })
