import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'billing',
  owns: [
    'apps/api/src/billing/**',
    'apps/api/src/routes/billing*',
    'apps/api/src/routes/subscription*',
    'apps/api/src/routes/invoice*',
    'apps/api/src/services/billing/**',
    'apps/api/src/services/payments/**',
    'apps/api/src/webhooks/billing/**',
    'apps/api/src/webhooks/stripe/**',
    'apps/api/src/webhooks/payments/**',
    'apps/web/src/app/(billing)/**',
    'apps/web/src/components/billing/**',
  ],
  allowedReads: [
    'apps/api/src/billing/**',
    'apps/api/src/routes/billing*',
    'apps/api/src/services/billing/**',
    'apps/api/src/webhooks/billing/**',
    'apps/api/src/db/schema/subscriptions*',
    'apps/api/src/db/schema/invoices*',
    'apps/api/src/db/schema/payments*',
    'apps/api/src/db/migrations/*billing*',
    'apps/api/src/db/migrations/*subscription*',
    'apps/api/src/db/migrations/*payment*',
    'tests/billing/**',
    'tests/integration/billing/**',
  ],
  allowedWrites: [
    'apps/api/src/billing/**',
    'apps/api/src/routes/billing*',
    'apps/api/src/services/billing/**',
    'apps/api/src/webhooks/billing/**',
    'tests/billing/**',
    'tests/integration/billing/**',
  ],
  relatedDomains: ['backend', 'database', 'tests', 'security'],
  forbiddenByDefault: [
    'apps/web/src/**',
    'apps/api/src/auth/**',
    'apps/api/src/routes/invite*',
    'secrets/**',
  ],
  riskProfile: [
    'payments',
    'billing',
    'PCI compliance',
    'financial data',
    'webhook idempotency',
    'refunds',
    'subscription state',
  ],
  verification: [
    'billing unit tests',
    'payment provider integration tests',
    'webhook idempotency tests',
    'currency / rounding tests',
    'subscription state machine tests',
  ],
  graphNodeIds: [
    'domain:billing',
    'service:PaymentService',
    'service:SubscriptionService',
    'webhook:POST /webhooks/stripe',
    'webhook:POST /webhooks/payments',
    'table:subscriptions',
    'table:invoices',
  ],
  graphEdgeIds: [
    'edge:PaymentService→table:payments',
    'edge:SubscriptionService→table:subscriptions',
    'edge:webhook:stripe→PaymentService',
  ],
  reviewSensitivity: 'critical',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'billing.trace_payment_flow',
    domain: 'billing',
    category: 'billing',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Trace a payment from checkout → webhook → DB. Returns the call chain and idempotency check.',
    inputHints: ['flow', 'provider'],
    tags: ['payment', 'billing', 'webhook', 'idempotency'],
    suggestedFollowUps: ['billing.find_webhook_handlers', 'db.check_query_impact'],
  },
  {
    name: 'billing.find_webhook_handlers',
    domain: 'billing',
    category: 'billing',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Locate every webhook handler (Stripe, payments, billing) and its idempotency strategy.',
    inputHints: ['provider'],
    tags: ['webhook', 'idempotency', 'billing'],
    suggestedFollowUps: ['billing.trace_payment_flow', 'tests.find_related_tests'],
  },
  {
    name: 'billing.explain_subscription_state_machine',
    domain: 'billing',
    category: 'billing',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Surface the subscription state transitions (active, past_due, canceled, paused) and the code paths that produce them.',
    inputHints: ['state'],
    tags: ['subscription', 'state', 'billing'],
    suggestedFollowUps: ['billing.find_webhook_handlers', 'tests.find_related_tests'],
  },
  {
    name: 'billing.estimate_refund_safety',
    domain: 'billing',
    category: 'billing',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Estimate the safety of a refund flow (idempotency, partial refund, currency, audit).',
    inputHints: ['scenario'],
    tags: ['refund', 'safety', 'billing', 'audit'],
    suggestedFollowUps: ['billing.trace_payment_flow', 'security.check_audit_logs'],
  },
  {
    name: 'billing.run_billing_regression_tests',
    domain: 'billing',
    category: 'billing',
    risk: 'medium',
    cost: 'high',
    gain: 'high',
    requiredPermissions: ['run_test', 'run_command'],
    description: 'Run the billing regression suite (payment flows, webhook idempotency, subscription state).',
    inputHints: ['scope'],
    tags: ['test', 'billing', 'regression'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
]

export const billingDomain: DomainEntry = Object.freeze({ manifest, capabilities })
