import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'database',
  owns: [
    'apps/api/src/db/**',
    'apps/api/src/db/schema/**',
    'apps/api/src/db/migrations/**',
    'apps/api/src/db/repos/**',
    'packages/db/**',
    'prisma/**',
    'drizzle/**',
  ],
  allowedReads: [
    'apps/api/src/db/**',
    'packages/db/**',
    'prisma/**',
    'drizzle/**',
    'tests/db/**',
    'tests/integration/db/**',
  ],
  allowedWrites: [
    'apps/api/src/db/schema/**',
    'apps/api/src/db/migrations/**',
    'apps/api/src/db/repos/**',
    'packages/db/**',
    'tests/db/**',
    'tests/integration/db/**',
  ],
  relatedDomains: ['backend', 'auth', 'tests', 'infra'],
  forbiddenByDefault: [
    'apps/web/**',
    'billing/**',
    'secrets/**',
    'infra/**',
  ],
  riskProfile: [
    'migrations',
    'data integrity',
    'data deletion',
    'concurrency',
    'schema drift',
    'backfill safety',
  ],
  verification: [
    'migration up/down tests',
    'repo unit tests',
    'migration idempotency tests',
    'seed/fixture tests',
    'integration tests touching migrated tables',
  ],
  graphNodeIds: [
    'domain:database',
    'table:users',
    'table:organizations',
    'table:invites',
    'table:roles',
    'migration:2026_06_15_add_invite_expiry',
  ],
  graphEdgeIds: [
    'edge:invite_repo→table:invites',
    'edge:InviteService→InviteRepo',
  ],
  reviewSensitivity: 'high',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'db.get_table_schema',
    domain: 'database',
    category: 'database',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_database_schema'],
    description: 'Return the schema (columns, types, indexes, constraints) of a given table.',
    inputHints: ['table'],
    tags: ['schema', 'table', 'column', 'index'],
    suggestedFollowUps: ['db.find_migrations_touching_table', 'db.check_query_impact'],
  },
  {
    name: 'db.find_migrations_touching_table',
    domain: 'database',
    category: 'migrations',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_migrations', 'read_database_schema'],
    description: 'List every migration that touched the given table, in chronological order, with diffs.',
    inputHints: ['table'],
    tags: ['migration', 'history', 'table', 'schema-evolution'],
    suggestedFollowUps: ['db.get_table_schema', 'db.check_query_impact'],
  },
  {
    name: 'db.check_query_impact',
    domain: 'database',
    category: 'database',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source', 'read_database_schema'],
    description: 'Estimate the impact of a query (tables, rows touched, indexes used, lock surface).',
    inputHints: ['query', 'tables'],
    tags: ['query', 'performance', 'index', 'lock'],
    suggestedFollowUps: ['db.get_table_schema', 'tests.find_related_tests'],
  },
  {
    name: 'db.run_migration_tests',
    domain: 'database',
    category: 'migrations',
    risk: 'medium',
    cost: 'medium',
    gain: 'high',
    requiredPermissions: ['run_test', 'run_command'],
    description: 'Run the migration up/down + idempotency suite.',
    inputHints: ['scope'],
    tags: ['migration', 'test', 'regression'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
  {
    name: 'db.estimate_backfill_safety',
    domain: 'database',
    category: 'migrations',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_migrations', 'read_database_schema'],
    description:
      'Estimate whether a proposed migration is safe for existing rows (backfill coverage, default values, NULL handling).',
    inputHints: ['migration', 'table'],
    tags: ['migration', 'backfill', 'safety', 'production'],
    suggestedFollowUps: ['db.find_migrations_touching_table', 'db.run_migration_tests'],
  },
]

export const databaseDomain: DomainEntry = Object.freeze({ manifest, capabilities })
