import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'frontend',
  owns: [
    'apps/web/**',
    'apps/web/src/**',
    'apps/web/src/components/**',
    'apps/web/src/pages/**',
    'apps/web/src/routes/**',
    'apps/web/src/hooks/**',
    'apps/web/src/state/**',
    'apps/web/src/lib/**',
    'apps/web/src/styles/**',
    'apps/web/src/api/**',
  ],
  allowedReads: [
    'apps/web/**',
    'packages/ui/**',
    'packages/shared/**',
    'apps/api/src/routes/**',
    'apps/api/src/db/schema/**',
  ],
  allowedWrites: [
    'apps/web/src/components/**',
    'apps/web/src/pages/**',
    'apps/web/src/routes/**',
    'apps/web/src/hooks/**',
    'apps/web/src/state/**',
    'apps/web/src/api/**',
    'apps/web/src/lib/**',
    'apps/web/src/styles/**',
    'tests/web/**',
    'tests/e2e/**',
  ],
  relatedDomains: ['backend', 'auth', 'tests', 'security'],
  forbiddenByDefault: [
    'apps/api/**',
    'billing/**',
    'infra/**',
    'secrets/**',
  ],
  riskProfile: [
    'user experience',
    'form validation',
    'client-side permissions',
    'accessibility',
    'visual regressions',
  ],
  verification: [
    'component unit tests',
    'page tests',
    'e2e flow tests',
    'visual regression tests',
    'accessibility tests',
  ],
  graphNodeIds: [
    'domain:frontend',
    'app:web',
    'component:InviteForm',
    'component:RoleSelect',
    'page:OrgSettings',
    'state:useInviteDraft',
  ],
  graphEdgeIds: [
    'edge:InviteForm→useInviteDraft',
    'edge:InviteForm→api.createInvite',
    'edge:OrgSettings→InviteForm',
  ],
  reviewSensitivity: 'medium',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'frontend.find_route_component',
    domain: 'frontend',
    category: 'frontend',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Locate the component that renders a given frontend route.',
    inputHints: ['path'],
    tags: ['route', 'component', 'page', 'ui'],
    suggestedFollowUps: ['frontend.find_state_owner', 'frontend.find_form_validation'],
  },
  {
    name: 'frontend.find_state_owner',
    domain: 'frontend',
    category: 'frontend',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Identify which hook, store, or context owns a given piece of client state.',
    inputHints: ['state'],
    tags: ['state', 'hook', 'store', 'context'],
    suggestedFollowUps: ['frontend.find_route_component', 'frontend.find_form_validation'],
  },
  {
    name: 'frontend.find_form_validation',
    domain: 'frontend',
    category: 'frontend',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Surface the form validation rules (required fields, formats, async checks) for a given form.',
    inputHints: ['form', 'field'],
    tags: ['form', 'validation', 'ux'],
    suggestedFollowUps: ['backend.find_request_validators', 'tests.find_related_tests'],
  },
  {
    name: 'frontend.run_visual_check',
    domain: 'frontend',
    category: 'verification',
    risk: 'low',
    cost: 'high',
    gain: 'medium',
    requiredPermissions: ['run_command'],
    description: 'Run a visual snapshot / e2e browser check for a given route or component.',
    inputHints: ['route', 'component'],
    tags: ['visual', 'e2e', 'screenshot'],
    suggestedFollowUps: ['tests.find_related_tests'],
  },
  {
    name: 'frontend.find_visual_regressions',
    domain: 'frontend',
    category: 'frontend',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Identify components with recent visual-regression diffs and the affected routes.',
    inputHints: [],
    tags: ['visual', 'regression', 'ui'],
    suggestedFollowUps: ['frontend.run_visual_check', 'frontend.find_route_component'],
  },
]

export const frontendDomain: DomainEntry = Object.freeze({ manifest, capabilities })
