import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'infra',
  owns: [
    'infra/**',
    'deploy/**',
    'docker/**',
    'Dockerfile',
    'docker-compose*.yml',
    'k8s/**',
    'kubernetes/**',
    'terraform/**',
    '.github/workflows/**',
    'scripts/ci/**',
    'scripts/deploy/**',
  ],
  allowedReads: [
    'infra/**',
    'deploy/**',
    'docker/**',
    '.github/**',
    'scripts/**',
    'package.json',
    'pnpm-workspace.yaml',
    'apps/api/**',
    'apps/web/**',
  ],
  allowedWrites: [
    'infra/**',
    'deploy/**',
    'docker/**',
    'k8s/**',
    'terraform/**',
    '.github/workflows/**',
    'scripts/ci/**',
    'scripts/deploy/**',
  ],
  relatedDomains: ['backend', 'database', 'security', 'tests'],
  forbiddenByDefault: [
    'apps/api/src/**',
    'apps/web/src/**',
    'billing/**',
    'secrets/**',
    'packages/auth/**',
  ],
  riskProfile: [
    'deployment',
    'CI runtime',
    'environment drift',
    'rollback safety',
    'secrets handling',
  ],
  verification: [
    'CI pipeline passes',
    'deployment dry-run',
    'infrastructure plan diff',
    'secrets scanning',
  ],
  graphNodeIds: [
    'domain:infra',
    'buildTarget:api',
    'buildTarget:web',
    'buildTarget:worker',
    'ci:github_actions',
  ],
  graphEdgeIds: [
    'edge:ci→buildTarget:api',
    'edge:ci→buildTarget:web',
  ],
  reviewSensitivity: 'high',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'infra.find_ci_target',
    domain: 'infra',
    category: 'infra',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Map a path or package to the CI jobs / build targets that exercise it.',
    inputHints: ['path', 'package'],
    tags: ['ci', 'build', 'target'],
    suggestedFollowUps: ['infra.run_typecheck', 'tests.select_affected_tests'],
  },
  {
    name: 'infra.run_typecheck',
    domain: 'infra',
    category: 'verification',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['run_typecheck', 'run_command'],
    description: 'Run TypeScript typecheck across the workspace. Always safe; high information on API drift.',
    inputHints: ['scope'],
    tags: ['typecheck', 'typescript', 'verification'],
    suggestedFollowUps: ['tests.run_verification_plan'],
  },
  {
    name: 'infra.run_lint',
    domain: 'infra',
    category: 'verification',
    risk: 'low',
    cost: 'low',
    gain: 'low',
    requiredPermissions: ['run_lint', 'run_command'],
    description: 'Run the linter and surface style / unused-export warnings.',
    inputHints: ['scope'],
    tags: ['lint', 'style', 'verification'],
    suggestedFollowUps: ['infra.run_typecheck'],
  },
  {
    name: 'infra.check_deployment_safety',
    domain: 'infra',
    category: 'infra',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Estimate deployment safety (migrations, breaking config, env-var additions).',
    inputHints: ['release', 'env'],
    tags: ['deploy', 'safety', 'release'],
    suggestedFollowUps: ['db.estimate_backfill_safety', 'tests.run_verification_plan'],
  },
  {
    name: 'infra.find_secrets_surface',
    domain: 'infra',
    category: 'security',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Identify files / paths that touch secrets (env vars, secret managers).',
    inputHints: ['path'],
    tags: ['secrets', 'security', 'compliance'],
    suggestedFollowUps: ['security.find_sensitive_paths', 'security.check_audit_logs'],
  },
]

export const infraDomain: DomainEntry = Object.freeze({ manifest, capabilities })
