import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'security',
  owns: [
    'apps/api/src/security/**',
    'apps/api/src/middleware/security/**',
    'apps/api/src/middleware/rateLimit*',
    'apps/api/src/middleware/cors*',
    'apps/api/src/middleware/csrf*',
    'apps/api/src/audit/**',
    'apps/api/src/services/audit/**',
  ],
  allowedReads: [
    'apps/api/src/security/**',
    'apps/api/src/middleware/**',
    'apps/api/src/audit/**',
    'apps/api/src/services/audit/**',
    'apps/api/src/auth/**',
    'apps/api/src/policies/**',
    'apps/api/src/db/schema/audit*',
    'apps/api/src/db/migrations/*audit*',
    'tests/security/**',
  ],
  allowedWrites: [
    'apps/api/src/security/**',
    'apps/api/src/middleware/security/**',
    'apps/api/src/middleware/rateLimit*',
    'apps/api/src/middleware/cors*',
    'apps/api/src/middleware/csrf*',
    'apps/api/src/audit/**',
    'apps/api/src/services/audit/**',
    'tests/security/**',
  ],
  relatedDomains: ['auth', 'backend', 'infra', 'tests'],
  forbiddenByDefault: [
    'apps/web/**',
    'billing/**',
    'secrets/**',
  ],
  riskProfile: [
    'security',
    'cryptography',
    'rate limiting',
    'CORS / CSRF',
    'audit log integrity',
    'secrets handling',
    'compliance',
  ],
  verification: [
    'security regression tests',
    'rate-limit tests',
    'CORS / CSRF tests',
    'audit log integrity tests',
    'penetration test artifacts',
  ],
  graphNodeIds: [
    'domain:security',
    'middleware:rateLimit',
    'middleware:cors',
    'middleware:csrf',
    'service:AuditService',
    'table:audit_log',
  ],
  graphEdgeIds: [
    'edge:AuditService→table:audit_log',
    'edge:rateLimit→route:invite',
  ],
  reviewSensitivity: 'critical',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'security.find_sensitive_paths',
    domain: 'security',
    category: 'security',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Identify paths that touch secrets, PII, or sensitive operations.',
    inputHints: ['path'],
    tags: ['secrets', 'pii', 'sensitive', 'security'],
    suggestedFollowUps: ['security.check_audit_logs', 'infra.find_secrets_surface'],
  },
  {
    name: 'security.check_audit_logs',
    domain: 'security',
    category: 'security',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Verify that a given action is recorded in the audit log and that the log write is transactional.',
    inputHints: ['action', 'actor'],
    tags: ['audit', 'log', 'compliance', 'security'],
    suggestedFollowUps: ['security.find_sensitive_paths', 'db.check_query_impact'],
  },
  {
    name: 'security.explain_rate_limit',
    domain: 'security',
    category: 'security',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Explain the rate-limit policy (per-actor, per-IP, per-route) and where it is enforced.',
    inputHints: ['route'],
    tags: ['rate-limit', 'middleware', 'security'],
    suggestedFollowUps: ['security.check_audit_logs', 'tests.find_related_tests'],
  },
  {
    name: 'security.check_cors_csrf',
    domain: 'security',
    category: 'security',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Inspect the CORS / CSRF configuration and the affected routes.',
    inputHints: ['route'],
    tags: ['cors', 'csrf', 'middleware', 'security'],
    suggestedFollowUps: ['security.check_audit_logs', 'tests.find_related_tests'],
  },
  {
    name: 'security.run_security_regression_tests',
    domain: 'security',
    category: 'security',
    risk: 'medium',
    cost: 'medium',
    gain: 'high',
    requiredPermissions: ['run_test', 'run_command'],
    description: 'Run the security regression suite (rate-limit, CORS, CSRF, audit-log integrity).',
    inputHints: ['scope'],
    tags: ['test', 'security', 'regression'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
]

export const securityDomain: DomainEntry = Object.freeze({ manifest, capabilities })
