import type { DomainManifest } from '@forge/types'
import type { CapabilityDescriptor, DomainEntry } from './schema.js'

const manifest: DomainManifest = {
  domain: 'tests',
  owns: [
    'tests/**',
    'tests/unit/**',
    'tests/integration/**',
    'tests/api/**',
    'tests/web/**',
    'tests/e2e/**',
    'tests/auth/**',
    'tests/db/**',
    'tests/visual/**',
  ],
  allowedReads: [
    'tests/**',
    'apps/api/**',
    'apps/web/**',
    'packages/**',
    '.github/workflows/**',
    'vitest.config.ts',
    'playwright.config.ts',
  ],
  allowedWrites: [
    'tests/**',
    'vitest.config.ts',
    'playwright.config.ts',
    'tests/fixtures/**',
  ],
  relatedDomains: ['backend', 'auth', 'database', 'frontend', 'verification'],
  forbiddenByDefault: [
    'apps/api/src/**',
    'apps/web/src/**',
    'billing/**',
    'infra/**',
    'secrets/**',
  ],
  riskProfile: [
    'test flakiness',
    'coverage gaps',
    'fixture drift',
    'CI runtime',
  ],
  verification: [
    'affected tests pass',
    'no coverage regression on touched code',
    'no new flaky tests',
    'CI runtime within budget',
  ],
  graphNodeIds: [
    'domain:tests',
    'suite:auth',
    'suite:api',
    'suite:web',
    'suite:e2e',
  ],
  graphEdgeIds: [
    'edge:suite:auth→auth',
    'edge:suite:api→backend',
    'edge:suite:e2e→frontend',
  ],
  reviewSensitivity: 'low',
}

const capabilities: CapabilityDescriptor[] = [
  {
    name: 'tests.find_related_tests',
    domain: 'tests',
    category: 'tests',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Find tests that exercise a given file, symbol, or behavior. Used to focus verification.',
    inputHints: ['file', 'symbol', 'behavior'],
    tags: ['test', 'related', 'selection'],
    suggestedFollowUps: ['tests.select_affected_tests', 'tests.run_verification_plan'],
  },
  {
    name: 'tests.select_affected_tests',
    domain: 'tests',
    category: 'tests',
    risk: 'low',
    cost: 'low',
    gain: 'high',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Map a set of changed files to the smallest credible test set. Considers flaky-test history.',
    inputHints: ['files', 'changedSymbols'],
    tags: ['test', 'selection', 'affected'],
    suggestedFollowUps: ['tests.run_verification_plan', 'tests.detect_coverage_gap'],
  },
  {
    name: 'tests.detect_coverage_gap',
    domain: 'tests',
    category: 'tests',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Compare touched code against existing tests. Surface symbols with no test references.',
    inputHints: ['files', 'symbols'],
    tags: ['coverage', 'gap', 'test'],
    suggestedFollowUps: ['tests.find_related_tests', 'tests.select_affected_tests'],
  },
  {
    name: 'tests.run_verification_plan',
    domain: 'tests',
    category: 'verification',
    risk: 'medium',
    cost: 'high',
    gain: 'high',
    requiredPermissions: ['run_test', 'run_command'],
    description: 'Run the test set produced by `tests.select_affected_tests` and report pass/fail + runtime.',
    inputHints: ['tests', 'scope'],
    tags: ['test', 'run', 'verification'],
    suggestedFollowUps: [],
  },
  {
    name: 'tests.check_flaky_history',
    domain: 'tests',
    category: 'tests',
    risk: 'low',
    cost: 'low',
    gain: 'medium',
    requiredPermissions: ['read_repo_graph', 'read_source'],
    description: 'Check the historical flakiness of a test (or suite). Used to de-prioritise unstable checks.',
    inputHints: ['test', 'suite'],
    tags: ['flaky', 'history', 'test'],
    suggestedFollowUps: ['tests.select_affected_tests'],
  },
]

export const testsDomain: DomainEntry = Object.freeze({ manifest, capabilities })
