/**
 * Markdown template for the belief + verification-state aware PR body.
 *
 * The body is composed in `renderPRBody` from a title, an 8-line summary, and
 * an ordered list of `PRGeneratorSection`. The template intentionally does
 * NOT hardcode section titles — those are driven by the section builder so
 * the sequence in `pr-generator.ts` is the single source of truth.
 *
 * Render order:
 *   1. `# <title>`                            ← from buildTitle()
 *   2. `<summary>`                            ← from buildSummary()
 *   3. `## <section.title>\n<section.markdown>` × N
 *   4. Footer with Forge attribution.
 */
import type { PRGeneratorSection } from '../types.js'

export interface PRBodyInput {
  title: string
  summary: string
  sections: PRGeneratorSection[]
}

export function renderPRBody(input: PRBodyInput): string {
  const out: string[] = []
  out.push(`# ${input.title}`, '')
  out.push(input.summary, '')

  for (const s of input.sections) {
    out.push(`## ${s.title}`, '')
    out.push(s.markdown, '')
  }

  out.push('---', '', '🤖 Generated by [Forge](https://github.com/coenhewes/forge)')
  return out.join('\n')
}
